#!/bin/sh

case "$1" in
    start)
        echo "Starting aesdsocket server"
        start-stop-daemon -n aesdsocket -S -a /usr/bin/aesdsocket -- -d
        ;;
    stop)
        echo "Stopping aesdsocket server"
        start-stop-daemon -n aesdsocket -K
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit 0
