#!/bin/sh
### BEGIN INIT INFO
# Provides:          aesdsocket-start-stop
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts aesdsocket server at boot
# Description:       This script starts and stops the aesdsocket server daemon.
### END INIT INFO

case "$1" in
    start)
        echo "Starting aesdsocket server"
        start-stop-daemon -n aesdsocket -S -a /usr/bin/aesdsocket -- -d
        ;;
    stop)
        echo "Stopping aesdsocket server"
        start-stop-daemon -n aesdsocket -K
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit 0
